# ============================================================
# Lokalni profil ? koristi se pri: mvn spring-boot:run
# postgres-tours kontejner mora biti pokrenut (docker compose up postgres-tours)
# Host port: 5435 (mapiran iz docker-compose.yml -> 5435:5432)
# ============================================================

# Database
spring.datasource.url=jdbc:postgresql://localhost:5435/tours_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

