spring:
  application:
    name: tour-service
  
  datasource:
    url: jdbc:postgresql://postgres-tours:5432/tours_db
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8083
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.soa: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
