// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/tour.proto

package tour

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{0}
}

type GetTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourRequest) Reset() {
	*x = GetTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourRequest) ProtoMessage() {}

func (x *GetTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourRequest.ProtoReflect.Descriptor instead.
func (*GetTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	LengthKm      float64                `protobuf:"fixed64,8,opt,name=length_km,json=lengthKm,proto3" json:"length_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_proto_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{2}
}

func (x *TourResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TourResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TourResponse) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *TourResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TourResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TourResponse) GetLengthKm() float64 {
	if x != nil {
		return x.LengthKm
	}
	return 0
}

type ToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*TourResponse        `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToursResponse) Reset() {
	*x = ToursResponse{}
	mi := &file_proto_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToursResponse) ProtoMessage() {}

func (x *ToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToursResponse.ProtoReflect.Descriptor instead.
func (*ToursResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{3}
}

func (x *ToursResponse) GetTours() []*TourResponse {
	if x != nil {
		return x.Tours
	}
	return nil
}

type PublishTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_proto_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{4}
}

func (x *PublishTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PublishTourRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type TourIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourIdRequest) Reset() {
	*x = TourIdRequest{}
	mi := &file_proto_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourIdRequest) ProtoMessage() {}

func (x *TourIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourIdRequest.ProtoReflect.Descriptor instead.
func (*TourIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{5}
}

func (x *TourIdRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type TourActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourActionResponse) Reset() {
	*x = TourActionResponse{}
	mi := &file_proto_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourActionResponse) ProtoMessage() {}

func (x *TourActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourActionResponse.ProtoReflect.Descriptor instead.
func (*TourActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_tour_proto_rawDescGZIP(), []int{6}
}

func (x *TourActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TourActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TourActionResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourActionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_tour_proto protoreflect.FileDescriptor

const file_proto_tour_proto_rawDesc = "" +
	"\n" +
	"\x10proto/tour.proto\x12\x04tour\"\a\n" +
	"\x05Empty\")\n" +
	"\x0eGetTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"\xd3\x01\n" +
	"\fTourResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tlength_km\x18\b \x01(\x01R\blengthKm\"9\n" +
	"\rToursResponse\x12(\n" +
	"\x05tours\x18\x01 \x03(\v2\x12.tour.TourResponseR\x05tours\"J\n" +
	"\x12PublishTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\"(\n" +
	"\rTourIdRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"y\n" +
	"\x12TourActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\atour_id\x18\x03 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xbf\x02\n" +
	"\vTourService\x125\n" +
	"\x11GetPublishedTours\x12\v.tour.Empty\x1a\x13.tour.ToursResponse\x127\n" +
	"\vGetTourById\x12\x14.tour.GetTourRequest\x1a\x12.tour.TourResponse\x12A\n" +
	"\vPublishTour\x12\x18.tour.PublishTourRequest\x1a\x18.tour.TourActionResponse\x12<\n" +
	"\vArchiveTour\x12\x13.tour.TourIdRequest\x1a\x18.tour.TourActionResponse\x12?\n" +
	"\x0eReactivateTour\x12\x13.tour.TourIdRequest\x1a\x18.tour.TourActionResponseB\vZ\t./pb/tourb\x06proto3"

var (
	file_proto_tour_proto_rawDescOnce sync.Once
	file_proto_tour_proto_rawDescData []byte
)

func file_proto_tour_proto_rawDescGZIP() []byte {
	file_proto_tour_proto_rawDescOnce.Do(func() {
		file_proto_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)))
	})
	return file_proto_tour_proto_rawDescData
}

var file_proto_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_tour_proto_goTypes = []any{
	(*Empty)(nil),              // 0: tour.Empty
	(*GetTourRequest)(nil),     // 1: tour.GetTourRequest
	(*TourResponse)(nil),       // 2: tour.TourResponse
	(*ToursResponse)(nil),      // 3: tour.ToursResponse
	(*PublishTourRequest)(nil), // 4: tour.PublishTourRequest
	(*TourIdRequest)(nil),      // 5: tour.TourIdRequest
	(*TourActionResponse)(nil), // 6: tour.TourActionResponse
}
var file_proto_tour_proto_depIdxs = []int32{
	2, // 0: tour.ToursResponse.tours:type_name -> tour.TourResponse
	0, // 1: tour.TourService.GetPublishedTours:input_type -> tour.Empty
	1, // 2: tour.TourService.GetTourById:input_type -> tour.GetTourRequest
	4, // 3: tour.TourService.PublishTour:input_type -> tour.PublishTourRequest
	5, // 4: tour.TourService.ArchiveTour:input_type -> tour.TourIdRequest
	5, // 5: tour.TourService.ReactivateTour:input_type -> tour.TourIdRequest
	3, // 6: tour.TourService.GetPublishedTours:output_type -> tour.ToursResponse
	2, // 7: tour.TourService.GetTourById:output_type -> tour.TourResponse
	6, // 8: tour.TourService.PublishTour:output_type -> tour.TourActionResponse
	6, // 9: tour.TourService.ArchiveTour:output_type -> tour.TourActionResponse
	6, // 10: tour.TourService.ReactivateTour:output_type -> tour.TourActionResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tour_proto_init() }
func file_proto_tour_proto_init() {
	if File_proto_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tour_proto_rawDesc), len(file_proto_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tour_proto_goTypes,
		DependencyIndexes: file_proto_tour_proto_depIdxs,
		MessageInfos:      file_proto_tour_proto_msgTypes,
	}.Build()
	File_proto_tour_proto = out.File
	file_proto_tour_proto_goTypes = nil
	file_proto_tour_proto_depIdxs = nil
}
