// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/tour.proto

package tour

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_GetPublishedTours_FullMethodName   = "/tour.TourService/GetPublishedTours"
	TourService_GetTourById_FullMethodName         = "/tour.TourService/GetTourById"
	TourService_PublishTour_FullMethodName         = "/tour.TourService/PublishTour"
	TourService_ArchiveTour_FullMethodName         = "/tour.TourService/ArchiveTour"
	TourService_ReactivateTour_FullMethodName      = "/tour.TourService/ReactivateTour"
	TourService_AddToCart_FullMethodName           = "/tour.TourService/AddToCart"
	TourService_Checkout_FullMethodName            = "/tour.TourService/Checkout"
	TourService_StartTourExecution_FullMethodName  = "/tour.TourService/StartTourExecution"
	TourService_CheckNearbyKeyPoint_FullMethodName = "/tour.TourService/CheckNearbyKeyPoint"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	GetPublishedTours(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToursResponse, error)
	GetTourById(ctx context.Context, in *GetTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	PublishTour(ctx context.Context, in *PublishTourRequest, opts ...grpc.CallOption) (*TourActionResponse, error)
	ArchiveTour(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourActionResponse, error)
	ReactivateTour(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourActionResponse, error)
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*CartResponse, error)
	Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
	StartTourExecution(ctx context.Context, in *StartTourExecutionRequest, opts ...grpc.CallOption) (*StartTourExecutionResponse, error)
	CheckNearbyKeyPoint(ctx context.Context, in *CheckNearbyKeyPointRequest, opts ...grpc.CallOption) (*CheckNearbyKeyPointResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetPublishedTours(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ToursResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ToursResponse)
	err := c.cc.Invoke(ctx, TourService_GetPublishedTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourById(ctx context.Context, in *GetTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) PublishTour(ctx context.Context, in *PublishTourRequest, opts ...grpc.CallOption) (*TourActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourActionResponse)
	err := c.cc.Invoke(ctx, TourService_PublishTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) ArchiveTour(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourActionResponse)
	err := c.cc.Invoke(ctx, TourService_ArchiveTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) ReactivateTour(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourActionResponse)
	err := c.cc.Invoke(ctx, TourService_ReactivateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*CartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CartResponse)
	err := c.cc.Invoke(ctx, TourService_AddToCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, TourService_Checkout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) StartTourExecution(ctx context.Context, in *StartTourExecutionRequest, opts ...grpc.CallOption) (*StartTourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_StartTourExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CheckNearbyKeyPoint(ctx context.Context, in *CheckNearbyKeyPointRequest, opts ...grpc.CallOption) (*CheckNearbyKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckNearbyKeyPointResponse)
	err := c.cc.Invoke(ctx, TourService_CheckNearbyKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
type TourServiceServer interface {
	GetPublishedTours(context.Context, *Empty) (*ToursResponse, error)
	GetTourById(context.Context, *GetTourRequest) (*TourResponse, error)
	PublishTour(context.Context, *PublishTourRequest) (*TourActionResponse, error)
	ArchiveTour(context.Context, *TourIdRequest) (*TourActionResponse, error)
	ReactivateTour(context.Context, *TourIdRequest) (*TourActionResponse, error)
	AddToCart(context.Context, *AddToCartRequest) (*CartResponse, error)
	Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error)
	StartTourExecution(context.Context, *StartTourExecutionRequest) (*StartTourExecutionResponse, error)
	CheckNearbyKeyPoint(context.Context, *CheckNearbyKeyPointRequest) (*CheckNearbyKeyPointResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) GetPublishedTours(context.Context, *Empty) (*ToursResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublishedTours not implemented")
}
func (UnimplementedTourServiceServer) GetTourById(context.Context, *GetTourRequest) (*TourResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourById not implemented")
}
func (UnimplementedTourServiceServer) PublishTour(context.Context, *PublishTourRequest) (*TourActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishTour not implemented")
}
func (UnimplementedTourServiceServer) ArchiveTour(context.Context, *TourIdRequest) (*TourActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveTour not implemented")
}
func (UnimplementedTourServiceServer) ReactivateTour(context.Context, *TourIdRequest) (*TourActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactivateTour not implemented")
}
func (UnimplementedTourServiceServer) AddToCart(context.Context, *AddToCartRequest) (*CartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToCart not implemented")
}
func (UnimplementedTourServiceServer) Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Checkout not implemented")
}
func (UnimplementedTourServiceServer) StartTourExecution(context.Context, *StartTourExecutionRequest) (*StartTourExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTourExecution not implemented")
}
func (UnimplementedTourServiceServer) CheckNearbyKeyPoint(context.Context, *CheckNearbyKeyPointRequest) (*CheckNearbyKeyPointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckNearbyKeyPoint not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call panics, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetPublishedTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetPublishedTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetPublishedTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetPublishedTours(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourById(ctx, req.(*GetTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_PublishTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).PublishTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_PublishTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).PublishTour(ctx, req.(*PublishTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_ArchiveTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ArchiveTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ArchiveTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ArchiveTour(ctx, req.(*TourIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_ReactivateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).ReactivateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_ReactivateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).ReactivateTour(ctx, req.(*TourIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_AddToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_Checkout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).Checkout(ctx, req.(*CheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_StartTourExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTourExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).StartTourExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_StartTourExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).StartTourExecution(ctx, req.(*StartTourExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CheckNearbyKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNearbyKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CheckNearbyKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CheckNearbyKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CheckNearbyKeyPoint(ctx, req.(*CheckNearbyKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublishedTours",
			Handler:    _TourService_GetPublishedTours_Handler,
		},
		{
			MethodName: "GetTourById",
			Handler:    _TourService_GetTourById_Handler,
		},
		{
			MethodName: "PublishTour",
			Handler:    _TourService_PublishTour_Handler,
		},
		{
			MethodName: "ArchiveTour",
			Handler:    _TourService_ArchiveTour_Handler,
		},
		{
			MethodName: "ReactivateTour",
			Handler:    _TourService_ReactivateTour_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _TourService_AddToCart_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _TourService_Checkout_Handler,
		},
		{
			MethodName: "StartTourExecution",
			Handler:    _TourService_StartTourExecution_Handler,
		},
		{
			MethodName: "CheckNearbyKeyPoint",
			Handler:    _TourService_CheckNearbyKeyPoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tour.proto",
}
